name: publish-release-action

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run tsc && vite build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: true
          files: dist/**
